/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.nbb.demetra.dstats;

import ec.nbdemetra.ui.DemetraUiIcon;
import java.awt.event.ActionEvent;
import javax.swing.*;
import org.openide.awt.DropDownButtonFactory;

final class Demo1Panel extends javax.swing.JPanel {

    private final Demo1OptionsPanelController controller;
    private final JPopupMenu dropDownMenu;

    Demo1Panel(Demo1OptionsPanelController controller) {
        this.controller = controller;
        dropDownMenu = new JPopupMenu();
        initComponents();
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        for (final DStatItem o : DStatItem.values()) {
            dropDownMenu.add(new AbstractAction(o.name()) {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int idx = jList1.getSelectedIndex();
                    DefaultListModel model = (DefaultListModel) jList1.getModel();
                    int newIdx = idx != -1 ? idx + 1 : model.getSize();
                    model.add(newIdx, o);
                    jList1.setSelectedIndex(newIdx);
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        addBtn = DropDownButtonFactory.createDropDownButton(DemetraUiIcon.LIST_ADD_16, dropDownMenu);
        removeBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(Demo1Panel.class, "Demo1Panel.jLabel1.text")); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/nbdemetra/ui/list-add_16x16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(addBtn, org.openide.util.NbBundle.getMessage(Demo1Panel.class, "Demo1Panel.addBtn.text")); // NOI18N
        addBtn.setFocusable(false);
        addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(addBtn);

        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/nbdemetra/ui/list-remove_16x16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(removeBtn, org.openide.util.NbBundle.getMessage(Demo1Panel.class, "Demo1Panel.removeBtn.text")); // NOI18N
        removeBtn.setEnabled(false);
        removeBtn.setFocusable(false);
        removeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(removeBtn);

        upBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/nbdemetra/ui/go-up_16x16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(upBtn, org.openide.util.NbBundle.getMessage(Demo1Panel.class, "Demo1Panel.upBtn.text")); // NOI18N
        upBtn.setEnabled(false);
        upBtn.setFocusable(false);
        upBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        upBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(upBtn);

        downBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/nbdemetra/ui/go-down_16x16.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(downBtn, org.openide.util.NbBundle.getMessage(Demo1Panel.class, "Demo1Panel.downBtn.text")); // NOI18N
        downBtn.setEnabled(false);
        downBtn.setFocusable(false);
        downBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        downBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(downBtn);

        jList1.setModel(new DefaultListModel());
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        int idx = jList1.getSelectedIndex();
        boolean enabled = idx != -1;
        removeBtn.setEnabled(enabled);
        upBtn.setEnabled(enabled && idx != 0);
        downBtn.setEnabled(enabled && idx != jList1.getModel().getSize() - 1);
    }//GEN-LAST:event_jList1ValueChanged

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        int idx = jList1.getSelectedIndex();
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.removeElementAt(idx);
        jList1.setSelectedIndex(idx);
    }//GEN-LAST:event_removeBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        int idx = jList1.getSelectedIndex();
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.add(idx - 1, model.remove(idx));
        jList1.setSelectedIndex(idx - 1);
    }//GEN-LAST:event_upBtnActionPerformed

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        int idx = jList1.getSelectedIndex();
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.add(idx + 1, model.remove(idx));
        jList1.setSelectedIndex(idx + 1);
    }//GEN-LAST:event_downBtnActionPerformed

    void load() {
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        model.clear();
        for (DStatItem o : DStatsHelper.ITEMS) {
            model.addElement(o);
        }
    }

    void store() {
        DStatsHelper.ITEMS.clear();
        DefaultListModel model = (DefaultListModel) jList1.getModel();
        for (Object o : model.toArray()) {
            DStatsHelper.ITEMS.add((DStatItem) o);
        }
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton downBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton upBtn;
    // End of variables declaration//GEN-END:variables
}
